../tests/write_read_test.v
../tests/tdr_wr_rd_test.v
../tests/tcr_wr_rd_test.v
../tests/tsr_wr_rd_test.v
../tests/timer_count_up_clk8_test.v
../tests/timer_count_up_clk2_test.v
../tests/timer_count_up_clk4_test.v
../tests/timer_count_up_clk16_test.v
../tests/timer_count_dw_clk2_test.v
../tests/timer_count_dw_clk4_test.v
../tests/timer_count_dw_clk8_test.v
../tests/timer_count_dw_clk16_test.v
../tests/timer_count_up_reset_test.v
../tests/timer_pause_down_test.v
../tests/timer_pause_up_test.v
../tests/timer_pause_updown_test.v
../tests/timer_pause_downup_test.v
../tests/timer_count_down_reset_test.v
../tests/timer_up_fake_ovf_test.v
../tests/timer_down_fake_udf_test.v

